import { createClient } from '@blinkdotnew/sdk';
const sdk:any=createClient({projectId:import.meta.env.VITE_BLINK_PROJECT_ID||'pocketpull-premium-site-b2nnhe2n',publishableKey:import.meta.env.VITE_BLINK_PUBLISHABLE_KEY||'blnk_pk_vT3Qhs4YE86jEwxvFWSg-5EcABJ06ofD',auth:{mode:'headless'}});
const API=import.meta.env.VITE_API_BASE_URL||'/api';
async function dbCall(collection:string,method:string,args:any[]){const token=await sdk.auth.getValidToken();let body:any={};if(method==='list'||method==='count'||method==='exists'){body={options:args[0]||{},where:(args[0]||{}).where||{}};}else if(method==='get'||method==='delete'){body={id:args[0]};}else if(method==='update'||method==='updateMany'){body={id:args[0],data:args[1]||{}};if(method==='updateMany')body={where:args[0]?.where||{},data:args[0]?.data||args[1]||{}};}else if(method==='create'||method==='upsert'||method==='createMany'){body={data:args[0]||[]};}const response=await fetch(`${API}/compat/db/${encodeURIComponent(collection)}/${method}`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||`Database API error ${response.status}`);return data;}
function collectionProxy(collection:string){return new Proxy({}, {get(_target,method:string){return (...args:any[])=>dbCall(collection,method,args);}});}
const db=new Proxy({}, {get(_target,property:string){if(property==='table')return (collection:string)=>collectionProxy(collection);return collectionProxy(property);}});
sdk.db=db;
export const blink=sdk;
export const INVENTORY_CHANNEL='inventory-updates';export const INVENTORY_UPDATED_EVENT='updated';export const BATTLE_CHANNEL_PREFIX='battle-state';export const BATTLE_LOBBY_CHANNEL='battle-lobby';export const BATTLE_EVENTS={PHASE_CHANGE:'phase_change',ROUND_UPDATE:'round_update',SPIN_TOGGLE:'spin_toggle',BATTLE_FINISHED:'battle_finished',RESULTS_READY:'results_ready',COUNTDOWN_UPDATE:'countdown_update',BATTLE_CANCELED:'battle_canceled'};
