import { Hono } from 'hono';
import { requireAuth, getBlinkServer, uid, getRewardUserId } from '../../lib/auth';
import { query } from '../../lib/postgres';
import { OpenedCard, BattlePullAudit } from './types';
import { rollBotWinChance, determineBattleWinner, distributeCardsShared, getWinnerPool, isExactTie, RARITY_EMOJIS } from './utils';
import { sha256, computeRoll, buildOddsSnapshot, selectCardIndex } from '../../lib/provablyFair';
import { getOrCreateServerSeed } from '../../lib/provablyFairServerSeed';
import { writeLog } from '../logs';
import { processWalletTransaction } from '../../lib/wallet';

const app = new Hono();
function parseBattlePlayers(players:any[]){return players.map(p=>({playerId:p.id,teamSide:p.teamSide||p.team_side||null,userId:p.userId,username:p.username,avatar:p.avatar,isAi:Number(p.isAi||p.is_ai||0)>0,cards:JSON.parse(p.cardsJson||p.cards_json||'[]'),totalValue:Number(p.totalValue||p.total_value||0),isWinner:Number(p.isWinner||p.is_winner||0)>0}));}
async function reconcilePersistedOutcome(blink:any,battle:any,players:any[],battleId:string){const results=parseBattlePlayers(players),mode=battle.mode||'standard',isTeamBattle=Number(battle.teamMode||battle.team_mode||0)>0;let winner:any=null,draw=false,winningTeam:'left'|'right'|null=null;if(mode==='shared')results.forEach(r=>{r.isWinner=true});else if(isTeamBattle){const left=results.filter(r=>r.teamSide==='left'),right=results.filter(r=>r.teamSide==='right'),leftTotal=Math.round(left.reduce((s,r)=>s+r.totalValue,0)*100),rightTotal=Math.round(right.reduce((s,r)=>s+r.totalValue,0)*100);if(leftTotal===rightTotal)draw=true;else{winningTeam=leftTotal>rightTotal?'left':'right';results.forEach(r=>{r.isWinner=r.teamSide===winningTeam});winner=results.find(r=>r.isWinner)||null;}}else{const pool=getWinnerPool(results,null);if(isExactTie(pool,mode))draw=true;else{winner=determineBattleWinner(pool,mode,null);results.forEach(r=>{r.isWinner=r.playerId===winner.playerId});}}for(const result of results)await blink.db.battlePlayers.update(result.playerId,{isWinner:result.isWinner?1:0});await blink.db.battles.update(battleId,{winnerUserId:winner?.userId||null,winnerUsername:winner?.username||null});await awardBattleCards(blink,battleId,mode,draw,isTeamBattle,winningTeam,winner,results);return{results,winner,draw};}
async function awardBattleCards(blink:any,battleId:string,mode:string,isDraw:boolean,isTeamBattle:boolean,winningTeam:'left'|'right'|null,winnerResult:any,playerResults:any[]){const existing=await blink.db.inventory.list({where:{battleId},limit:1}) as any[];if(existing.length>0)return;const inventoryToCreate:any[]=[];const addCard=(card:any,recipient:any)=>{const recipientId=getRewardUserId(recipient.userId,recipient.isAi);inventoryToCreate.push({id:`inv_${uid()}`,userId:recipientId,battleId,cardId:`${String(card.name||'').toLowerCase().replace(/\s+/g,'_')}_${card.rarity}`,cardName:card.name,rarity:card.rarity,value:card.value,emoji:RARITY_EMOJIS[card.rarity]||'🃏',isFavorite:0,cardImageUrl:card.imageUrl||null,packName:card.packName});};if(mode==='shared'||isDraw){for(const player of playerResults)for(const card of player.cards||[])addCard(card,player);}else if(isTeamBattle&&winningTeam){const winningPlayers=playerResults.filter(p=>p.teamSide===winningTeam),allCards=playerResults.flatMap(p=>p.cards||[]);allCards.forEach((card:any,index:number)=>{const recipient=winningPlayers[index%winningPlayers.length];if(recipient)addCard(card,recipient);});}else if(winnerResult){for(const card of playerResults.flatMap(p=>p.cards||[]))addCard(card,winnerResult);}if(inventoryToCreate.length>0){console.log(`[Battle Reward] Creating ${inventoryToCreate.length} inventory items for battle ${battleId}`);await blink.db.inventory.createMany(inventoryToCreate);}}

app.post('/execute',async(c)=>{let userId:string;try{userId=await requireAuth(c);}catch(err:any){if(err.message==='ACCOUNT_DEACTIVATED')return c.json({error:'Account deactivated'},403);return c.json({error:'Authentication required'},401);}const blink=getBlinkServer(c.env as any);try{const body=await c.req.json(),{battleId}=body;if(!battleId)return c.json({error:'battleId required'},400);const battle=await blink.db.battles.get(battleId) as any;if(!battle)return c.json({error:'Battle not found'},404);if(battle.hostUserId!==userId)return c.json({error:'Only host can execute battle'},403);if(battle.status==='finished'||battle.status==='live'){const players=await blink.db.battlePlayers.list({where:{battleId}}) as any[];const hasCompleteResults=players.length>0&&players.every(p=>JSON.parse(p.cardsJson||p.cards_json||'[]').length>0);if(hasCompleteResults){const outcome=await reconcilePersistedOutcome(blink,battle,players,battleId);return c.json({success:true,playerResults:outcome.results,winner:outcome.winner,isDraw:outcome.draw});}}if(battle.status!=='waiting'&&battle.status!=='starting')return c.json({error:`Battle is in status ${battle.status}`},400);
const { seed: serverSeed, seedHash: actualSeedHash } = await getOrCreateServerSeed((c.env as any).BLINK_SERVER_SEED);
const claimed=await query<{id:string}>('UPDATE battles SET status=$1,started_at=COALESCE(started_at,now()) WHERE id=$2 AND status IN ($3,$4) RETURNING id',['live',battleId,'waiting','starting']);if(!claimed.length)return c.json({error:'Battle execution already in progress'},409);
const battlePacks=JSON.parse(battle.packsJson||'[]');const players=await blink.db.battlePlayers.list({where:{battleId}}) as any[];const hasCompleteResults=players.length>0&&players.every(p=>JSON.parse(p.cardsJson||p.cards_json||'[]').length>0);if(hasCompleteResults){const outcome=await reconcilePersistedOutcome(blink,{...battle,status:'live'},players,battleId);await blink.db.battles.update(battleId,{status:'finished',endedAt:battle.endedAt||new Date().toISOString(),isSpinning:0,winnerUserId:outcome.winner?.userId||null,winnerUsername:outcome.winner?.username||null});return c.json({success:true,playerResults:outcome.results,winner:outcome.winner,isDraw:outcome.draw});}
const packIds=[...new Set(battlePacks.map((p:any)=>p.id))] as string[];const allPackCards=await blink.db.packCards.list({where:{packId:{in:packIds}},limit:1000}) as any[];const packCardsMap:Record<string,any[]>={};for(const pid of packIds)packCardsMap[pid]=allPackCards.filter(c=>c.packId===pid);const packOddsHashes:Record<string,string>={};for(const pid of packIds){const dbCards=packCardsMap[pid]||[];if(dbCards.length>0){const oddsJson=buildOddsSnapshot(dbCards),oddsHash=await sha256(oddsJson);packOddsHashes[pid]=oddsHash;try{await blink.db.table('packOddsVersions').upsert({contentHash:oddsHash,packId:pid,oddsJson,cardCount:dbCards.length});}catch{}}}
const mode=battle.mode||'standard';const playerResults:any[]=[],poLogs:any[]=[],battlePullAudits:BattlePullAudit[]=[],letBattlePullIndex=0;let battlePullIndex=0;for(const player of players){const cards:OpenedCard[]=[],isPlayerAi=Number(player.isAi||player.is_ai||0)>0,playerUserId=player.userId||player.user_id;for(const bPack of battlePacks){battlePullIndex++;const dbCards=packCardsMap[bPack.id]||[];if(!dbCards.length)continue;const oddsHash=packOddsHashes[bPack.id]||'';let nonce:number;if(isPlayerAi)nonce=battlePullIndex;else{try{await blink.db.sql(`INSERT INTO user_nonces (user_id, pack_nonce) VALUES (?, 1) ON CONFLICT(user_id) DO UPDATE SET pack_nonce = pack_nonce + 1`,[playerUserId]);const nonceRows=await blink.db.table('userNonces').list({where:{userId:playerUserId},limit:1}) as any[];nonce=nonceRows.length&&nonceRows[0].packNonce!==undefined?Number(nonceRows[0].packNonce):nonceRows.length&&nonceRows[0].pack_nonce!==undefined?Number(nonceRows[0].pack_nonce):battlePullIndex;}catch{return c.json({error:'Provably fair system error — nonce persistence failed. Please try again.'},500);}}const clientSeed=`cs_bt_${uid()}`,rollValue=await computeRoll(serverSeed,clientSeed,nonce),cardIndex=selectCardIndex(rollValue,dbCards),pickedRaw:any=dbCards[cardIndex],cardRarity=pickedRaw.rarity||'common';const card:any={id:`po_${uid()}`,name:pickedRaw.cardName||pickedRaw.card_name||'Unknown Card',rarity:cardRarity,value:Number(pickedRaw.estimatedValue??pickedRaw.estimated_value??0),imageUrl:pickedRaw.cardImageUrl||pickedRaw.card_image_url||null,packId:bPack.id,packName:bPack.name,emoji:RARITY_EMOJIS[cardRarity]||'🃏',clientSeed,nonce,rollValue,serverSeedHash:actualSeedHash,oddsVersionHash:oddsHash,isBot:isPlayerAi};if(!isPlayerAi)poLogs.push({id:`po_bt_${uid()}`,userId:playerUserId,packId:bPack.id,packName:bPack.name,cost:Number(bPack.price),cardName:card.name,rarity:card.rarity,clientSeed,nonce,rollValue,serverSeedHash:actualSeedHash,oddsVersionHash:oddsHash,provablyFair:1});battlePullAudits.push({id:`bpa_${uid()}`,battleId,battlePlayerId:player.id,userId:playerUserId,packId:bPack.id,packName:bPack.name,cardName:card.name,rarity:card.rarity,cost:Number(bPack.price),clientSeed,nonce,rollValue,serverSeedHash:actualSeedHash,oddsVersionHash:oddsHash,isBot:isPlayerAi?1:0});cards.push(card);}const total=cards.reduce((s:number,c:any)=>s+(c.value??0),0);playerResults.push({playerId:player.id,teamSide:player.teamSide||player.team_side||null,userId:playerUserId,username:player.username,avatar:player.avatar,isAi:isPlayerAi,cards,totalValue:Math.round(total*100)/100,isWinner:false});}
try{await blink.db.table('battlePullAudits').createMany(battlePullAudits);}catch{}if(poLogs.length>0)blink.db.packsOpened.createMany(poLogs).catch(()=>{});
let botFaction:'bot'|'human'|null=null,isDraw=false;if(mode==='underdog'){const hasBots=playerResults.some(r=>r.isAi),hasHumans=playerResults.some(r=>!r.isAi);if(hasBots&&hasHumans){const diceClientSeed=`dice_${battleId}`,diceNonce=battlePullIndex+1,diceRoll=await computeRoll(serverSeed,diceClientSeed,diceNonce);botFaction=rollBotWinChance(playerResults,mode,diceRoll);battlePullAudits.push({id:`bpa_dice_${uid()}`,battleId,battlePlayerId:'system',userId:'system',packId:'system',packName:'[BATTLE_DICE]',cardName:`Underdog dice — faction: ${botFaction}`,rarity:'system',cost:0,clientSeed:diceClientSeed,nonce:diceNonce,rollValue:diceRoll,serverSeedHash:actualSeedHash,oddsVersionHash:'',isBot:0});blink.db.table('battlePullAudits').createMany([battlePullAudits[battlePullAudits.length-1]]).catch(()=>{});}}
let winnerResult:any=null,winningTeam:'left'|'right'|null=null;if(mode!=='shared'&&playerResults.length>0&&Number(battle.teamMode||battle.team_mode)===0){const pool=getWinnerPool(playerResults,botFaction);if(isExactTie(pool,mode))isDraw=true;else{winnerResult=determineBattleWinner(pool,mode,botFaction);if(!winnerResult)throw new Error('Unable to determine a winner for this battle');playerResults.forEach(r=>{r.isWinner=r.playerId===winnerResult.playerId});}}
const isTeamBattle=Number(battle.teamMode||battle.team_mode)>0;if(isTeamBattle){const leftTotalCents=Math.round(playerResults.filter(r=>r.teamSide==='left').reduce((s,r)=>s+Number(r.totalValue||0),0)*100),rightTotalCents=Math.round(playerResults.filter(r=>r.teamSide==='right').reduce((s,r)=>s+Number(r.totalValue||0),0)*100);if(leftTotalCents===rightTotalCents)isDraw=true;else{winningTeam=leftTotalCents>rightTotalCents?'left':'right';playerResults.forEach(r=>{r.isWinner=r.teamSide===winningTeam});winnerResult=playerResults.find(r=>r.teamSide===winningTeam)||null;}}
if(mode==='shared'){playerResults.forEach(r=>{r.isWinner=true});const distribution=distributeCardsShared(playerResults.map(p=>({playerId:p.playerId,cards:p.cards as OpenedCard[]})));for(const pr of playerResults){const share=distribution.get(pr.playerId)||[];pr.cards=share;pr.totalValue=Math.round(share.reduce((s:number,c:any)=>s+(c.value??0),0)*100)/100;}}
for(const pr of playerResults)await blink.db.battlePlayers.update(pr.playerId,{cardsJson:JSON.stringify(pr.cards),totalValue:pr.totalValue,isWinner:pr.isWinner?1:0});await awardBattleCards(blink,battleId,mode,isDraw,isTeamBattle,winningTeam,winnerResult,playerResults);
if(!isDraw&&mode!=='shared'&&winnerResult&&!winnerResult.isAi){try{const wUserId=winnerResult.userId,totalValue=winnerResult.totalValue,packsCount=battlePacks.length,existingStats=await blink.db.leaderboardStats.list({where:{id:wUserId}}) as any[],ls=existingStats[0];if(ls)await blink.db.leaderboardStats.update(ls.id,{packsOpened:Number(ls.packsOpened||0)+packsCount,biggestPull:Math.max(Number(ls.biggestPull||0),totalValue),updatedAt:new Date().toISOString()});else await blink.db.leaderboardStats.create({id:wUserId,username:winnerResult.username,biggestPull:totalValue,packsOpened:packsCount,winStreak:0,upgradesAttempted:0,updatedAt:new Date().toISOString()});}catch(e:any){console.error('[Battle Reward] Failed to update leaderboard stats:',e.message);}}
if(isTeamBattle&&winningTeam&&!isDraw){const winningPlayers=playerResults.filter(r=>r.teamSide===winningTeam&&!r.isAi),teamPot=Number(battle.totalCost)*playerResults.length,share=teamPot/Math.max(winningPlayers.length,1);for(const player of winningPlayers)await processWalletTransaction(blink,{userId:player.userId,type:'battle_team_reward',amount:share,sourceId:`${battleId}_${winningTeam}`,metadata:{teamSide:winningTeam,teamPot,share}});}
await blink.db.battles.update(battleId,{status:'finished',endedAt:new Date().toISOString(),isSpinning:0,winnerUserId:winnerResult?.userId||null,winnerUsername:winnerResult?.username||null});try{const packs=JSON.parse(battle.packsJson||'[]'),packNames=packs.map((p:any)=>p.name).join(', '),totalPot2=Number(battle.totalCost)*playerResults.length,resultLabel=isDraw?'draw':'completed';await writeLog(blink,{type:'battle',userId:(isDraw||mode==='shared')?null:(winnerResult?.userId||null),username:isDraw?'Draw':(mode==='shared'?'Shared':(winnerResult?.username||'Unknown')),action:`Pack Battle ${isDraw?'(Draw)':mode==='shared'?'(Shared)':mode==='underdog'?'(Underdog)':'(Standard)'}`,details:{battleId,mode,isDraw,packNames,players:playerResults.map(pr=>({username:pr.username,isAi:pr.isAi,totalValue:pr.totalValue,isWinner:pr.isWinner,cards:pr.cards.slice(0,5).map((c:any)=>({name:c.name,value:c.value,rarity:c.rarity}))})),winner:(isDraw||mode==='shared')?null:(winnerResult?{username:winnerResult.username,totalValue:winnerResult.totalValue}:null),totalPot:totalPot2},valueIn:totalPot2,valueOut:isDraw?0:(mode==='shared'?totalPot2:(winnerResult?.totalValue||0)),result:resultLabel});}catch{}
return c.json({success:true,playerResults,winner:winnerResult,isDraw});}catch(err:any){console.error('[battles/execute] error:',err.message);return c.json({error:err.message||'Internal server error'},500);}});
export default app;
