import { Hono } from 'hono'; import { requireAuth,getBlinkServer } from '../lib/auth';
const app=new Hono();
async function requireAdmin(c:any){const b=getBlinkServer(c.env as any),pass=c.req.header('X-Admin-Password')||c.req.header('X-Admin-Secret');if(pass&&pass!=='true'){const rows=await b.db.adminCredentials.list({});if(rows.some((r:any)=>(r.adminPass||r.admin_pass)===pass))return b.db;}const id=await requireAuth(c),u=await b.db.users.get(id) as any;if(!u||!['admin','owner'].includes(u.role))throw new Error('FORBIDDEN');return b.db;}
app.post('/admin/auth/login',async c=>{try{const {identifier,password}=await c.req.json();const db=getBlinkServer(c.env as any).db,rows=await db.adminCredentials.list({});const match=rows.find((r:any)=>String(r.username||'').toLowerCase()===String(identifier||'').toLowerCase()||String(r.email||'').toLowerCase()===String(identifier||'').toLowerCase());if(match&&(match.adminPass||match.admin_pass)===password)return c.json({success:true,adminPassword:password});return c.json({error:'Invalid username or password.'},401)}catch{return c.json({error:'Invalid username or password.'},401)}});
app.use('/admin/packs/*',async(c,n)=>{try{await requireAdmin(c);await n()}catch(e:any){return c.json({error:e.message==='FORBIDDEN'?'Admin access required':'Authentication required'},e.message==='FORBIDDEN'?403:401)}});
app.get('/admin/packs',async c=>{try{const db=await requireAdmin(c),[packs,cards]=await Promise.all([db.packsCatalog.list({orderBy:{sortOrder:'asc'}}),db.packCards.list({orderBy:{sortOrder:'asc'}})]);return c.json({packs,cards})}catch(e:any){return c.json({error:e.message||'Failed to load packs'},500)}});
app.post('/admin/packs',async c=>{try{const db=await requireAdmin(c),{pack,cards=[]}=await c.req.json();if(!pack?.id||!pack?.name)return c.json({error:'Pack id and name are required'},400);await db.packsCatalog.upsert(pack);await db.packCards.deleteMany({where:{packId:pack.id}});if(cards.length)await db.packCards.createMany(cards);return c.json({success:true})}catch(e:any){return c.json({error:e.message||'Failed to save pack'},500)}});
app.patch('/admin/packs/:id',async c=>{try{const db=await requireAdmin(c);await db.packsCatalog.update(c.req.param('id'),await c.req.json());return c.json({success:true})}catch(e:any){return c.json({error:e.message||'Failed to update pack'},500)}});
app.delete('/admin/packs/:id',async c=>{try{const db=await requireAdmin(c),id=c.req.param('id');await db.packCards.deleteMany({where:{packId:id}});await db.packsCatalog.delete(id);return c.json({success:true})}catch(e:any){return c.json({error:e.message||'Failed to delete pack'},500)}});
export default app;
