import { Hono } from 'hono'; import { formatDistanceToNow } from 'date-fns'; import { getBlinkServer,requireAuth } from '../lib/auth';
const app=new Hono();const db=(c:any)=>getBlinkServer(c.env as any).db;
const normalizePack=(p:any)=>({...p,packType:p.packType==='mystery'?'mystery':'standard',price:Number(p.price),sortOrder:Number(p.sortOrder||0),isActive:Number(p.isActive??1),quantityLimit:Number(p.quantityLimit||0),currentQuantity:Number(p.currentQuantity||0),cooldownHours:Number(p.cooldownHours||0),expiresAt:p.expiresAt||null,nameColor:p.nameColor||'#fff',descriptionColor:p.descriptionColor||'#fff',priceColor:p.priceColor||'#fff',buttonTextColor:p.buttonTextColor||'#fff',openAnotherButtonTextColor:p.openAnotherButtonTextColor||p.buttonTextColor||'#fff'});const normalizeCard=(x:any)=>({...x,pullChance:Number(x.pullChance||0),estimatedValue:Number(x.estimatedValue||0),sortOrder:Number(x.sortOrder||0),quantity:Number(x.quantity||0),originalQuantity:Number(x.originalQuantity??x.quantity??0)});
async function visibleUsers(database:any,ids:string[]){if(!ids.length)return new Map();const rows=await database.users.list({where:{id:{in:ids}}});return new Map(rows.filter((u:any)=>!Number(u.isDeleted||0)&&!Number(u.isBanned||0)).map((u:any)=>[u.id,u.username||u.displayName||'Trainer']))}
app.get('/catalog/packs',async c=>{try{return c.json({packs:(await db(c).packsCatalog.list({where:{isActive:1},orderBy:{price:'asc'}})).map(normalizePack)})}catch{return c.json({error:'Failed to load packs'},500)}});
app.get('/catalog/packs/:packId/cards',async c=>{try{const database=db(c),p=await database.packsCatalog.get(c.req.param('packId')) as any;if(!p||Number(p.isActive)!==1)return c.json({error:'Pack not found'},404);return c.json({cards:(await database.packCards.list({where:{packId:p.id},orderBy:{sortOrder:'asc'}})).map(normalizeCard)})}catch{return c.json({error:'Failed to load pack cards'},500)}});
app.get('/catalog/cooldowns',async c=>{try{return c.json({cooldowns:await db(c).packCooldowns.list({where:{userId:await requireAuth(c)}})})}catch{return c.json({error:'Authentication required'},401)}});
app.get('/catalog/all-cards',async c=>{try{const database=db(c),packs=(await database.packsCatalog.list({where:{isActive:1}})).filter((p:any)=>(p.packType||'standard')==='standard');if(!packs.length)return c.json({cards:[]});const ids=packs.map((p:any)=>p.id),map=new Map(packs.map((p:any)=>[p.id,p.name])),cards=await database.packCards.list({orderBy:{estimatedValue:'desc'},limit:3000});return c.json({cards:cards.filter((x:any)=>ids.includes(x.packId)).map((x:any)=>({...normalizeCard(x),packName:map.get(x.packId)||'Mystery Pack'}))})}catch{return c.json({error:'Failed to load cards'},500)}});
app.get('/catalog/recent-pulls',async c=>{try{const database=db(c),limit=Math.min(100,Math.max(1,Number(c.req.query('limit')||12))),pulls=await database.inventory.list({orderBy:{createdAt:'desc'},limit}),map=await visibleUsers(database,[...new Set(pulls.map((p:any)=>p.userId).filter(Boolean))]);return c.json({pulls:pulls.map((p:any)=>({...p,user:map.get(p.userId)||'Trainer',time:p.createdAt?formatDistanceToNow(new Date(p.createdAt),{addSuffix:true}):''}))})}catch{return c.json({error:'Failed to load recent pulls'},500)}});
app.get('/catalog/hall-of-fame',async c=>{try{const database=db(c),limit=Math.min(50,Math.max(1,Number(c.req.query('limit')||5))),pulls=await database.inventory.list({orderBy:{value:'desc'},limit}),map=await visibleUsers(database,[...new Set(pulls.map((p:any)=>p.userId).filter(Boolean))]);return c.json({pulls:pulls.filter((p:any)=>map.has(p.userId)).map((p:any)=>({...p,user:map.get(p.userId),time:p.createdAt?formatDistanceToNow(new Date(p.createdAt),{addSuffix:true}):''}))})}catch{return c.json({error:'Failed to load Hall of Fame'},500)}});
app.get('/catalog/god-pulls',async c=>{try{const database=db(c),cards=await database.packCards.list({where:{rarity:'god'},limit:50}),ids=[...new Set(cards.map((x:any)=>x.packId).filter(Boolean))],packs=ids.length?await database.packsCatalog.list({where:{id:{in:ids}}}):[],map=new Map(packs.map((p:any)=>[p.id,p.name]));return c.json({cards:cards.map((x:any)=>({id:x.id,name:x.cardName,rarity:x.rarity,value:Number(x.estimatedValue)||0,imageUrl:x.cardImageUrl,packName:map.get(x.packId)||'Mystery Pack',glow:'#ff00ff'}))})}catch{return c.json({error:'Failed to load God pulls'},500)}});export default app;
