import { Hono } from 'hono';
import { getBlinkServer, uid } from '../lib/auth';
import { writeLog } from './logs';
import { processFirstDepositBonus, processReferralReward } from '../lib/payments';
import { processWalletTransaction } from '../lib/wallet';
import { SignJWT, importPKCS8 } from 'jose';
const app=new Hono();
async function generateCDPToken(keyId:string,privateKey:string){let key=privateKey.split('\\n').join('\n').trim();if(!key.startsWith('-----BEGIN'))key=`-----BEGIN PRIVATE KEY-----\n${key}\n-----END PRIVATE KEY-----`;const pkcs8=await importPKCS8(key,'ES256');const now=Math.floor(Date.now()/1000);return new SignJWT({}).setProtectedHeader({alg:'ES256',kid:keyId,typ:'JWT'}).setIssuer('cdp').setSubject(`cdp:${keyId}`).setAudience('cdp').setIssuedAt(now).setNotBefore(now-30).setExpirationTime(now+60).setJti(uid()).sign(pkcs8);}
app.post('/create-coinbase-charge',async c=>{const blink=getBlinkServer(c.env as any);try{const {amountUsd,userId,username:bodyUsername}=await c.req.json().catch(()=>({}));if(!amountUsd||parseFloat(amountUsd)<5)return c.json({error:'Minimum deposit is $5.00'},400);if(!userId)return c.json({error:'User ID is required'},400);const keyId=c.env.COINBASE_CDP_KEY_ID,secret=c.env.COINBASE_CDP_KEY_SECRET;if(!keyId||!secret)return c.json({error:'Coinbase CDP keys not configured.'},500);const u=await blink.db.users.get(userId) as any;const username=bodyUsername||u?.username||u?.displayName||'Trainer';const amt=parseFloat(amountUsd);const token=await generateCDPToken(keyId,secret);const res=await fetch('https://api.commerce.coinbase.com/charges',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,'X-CC-Version':'2018-03-22','User-Agent':'PocketPull/1.0.0'},body:JSON.stringify({name:'PocketPull Deposit',description:`Add ${amt.toFixed(2)} to your PocketPull balance`,pricing_type:'fixed_price',local_price:{amount:amt.toFixed(2),currency:'USD'},metadata:{user_id:userId,username,amount_usd:String(amountUsd)},redirect_url:'https://pocketpulltcg.com?deposit=success',cancel_url:'https://pocketpulltcg.com?deposit=cancelled'})});const data=await res.json().catch(()=>({}));if(!res.ok)return c.json({error:data?.error?.message||data?.message||'CDP API failed'},res.status as any);return c.json({chargeId:data.data.id,hostedUrl:data.data.hosted_url,expiresAt:data.data.expires_at});}catch(err:any){return c.json({error:err.message||'Internal Server Error'},500);}});
app.get('/coinbase-charge-status',async c=>{const blink=getBlinkServer(c.env as any);const chargeId=c.req.query('chargeId'),userId=c.req.query('userId');if(!chargeId||!userId)return c.json({error:'chargeId and userId required'},400);try{const txn=await blink.db.transactions.get(`txn_coinbase_${chargeId}`);if(!txn)return c.json({confirmed:false});const user=await blink.db.users.get(userId) as any;return c.json({confirmed:true,newBalance:Number(user?.balance||0)});}catch(err:any){return c.json({error:err.message},500);}});
app.post('/webhook/coinbase',async c=>{const blink=getBlinkServer(c.env as any);const raw=await c.req.text(),sig=c.req.header('X-CC-Webhook-Signature'),secret=c.env.COINBASE_WEBHOOK_SECRET;if(!sig||!secret)return c.text('Missing signature or secret',400);try{const enc=new TextEncoder(),key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),buf=await crypto.subtle.sign('HMAC',key,enc.encode(raw)),expected=Array.from(new Uint8Array(buf)).map(b=>b.toString(16).padStart(2,'0')).join('');if(sig!==expected)return c.text('Invalid signature',400);}catch{return c.text('Signature verification error',400);}let event:any;try{event=JSON.parse(raw)}catch{return c.text('Invalid JSON body',400)};if(['checkout.payment.success','charge:confirmed','charge:resolved'].includes(event.type||'')){const charge=event.data||{};const meta=charge.metadata||{};const userId=meta.user_id||meta.userId,username=meta.username||'Trainer',amount=meta.amount_usd||meta.amountUsd;if(userId&&amount)try{await processCoinbaseDeposit(blink,charge.id,userId,username,parseFloat(amount));}catch(err:any){console.error('[Coinbase]',err.message)}}return c.json({received:true});});
async function processCoinbaseDeposit(blink:any,chargeId:string,userId:string,username:string,depositAmt:number){const txnId=`txn_coinbase_${chargeId}`;if(await blink.db.transactions.get(txnId))return{status:'already_processed'};const user=await blink.db.users.get(userId);if(!user)return{error:'User not found'};const wallet=await processWalletTransaction(blink,{userId,type:'deposit',amount:depositAmt,sourceId:chargeId});if(!wallet.success)return{error:wallet.error||'Failed to credit balance'};await blink.db.transactions.create({id:txnId,userId,type:'deposit',amount:depositAmt,description:`Coinbase deposit — ${depositAmt.toFixed(2)} · ${username}`});try{await writeLog(blink,{type:'deposit',userId,username,action:'Coinbase Deposit Confirmed',details:{amount:depositAmt,chargeId,paymentMethod:'Coinbase',status:'completed'},valueIn:depositAmt,valueOut:0,result:'success'});}catch{};const u=user as any;if(!u.firstDepositBonusPaid)await processFirstDepositBonus(blink,userId,depositAmt);if(depositAmt>=5&&u.referredById&&!u.referralRewardPaid)await processReferralReward(blink,userId,u.referredById,depositAmt);return{status:'success',newBalance:wallet.balanceAfter};}
export default app;
