import { Hono } from 'hono';
import { requireAuth } from '../lib/auth';
import { setInventoryFlag, getOwnedInventory, sellInventory } from '../repositories/inventory';
import { query } from '../lib/postgres';
import { processWalletTransaction } from '../lib/wallet';

const app = new Hono();
async function auth(c:any){try{return await requireAuth(c);}catch(e:any){if(e.message==='ACCOUNT_DEACTIVATED')return c.json({error:'Account deactivated'},403);return c.json({error:'Authentication required'},401);}}

app.post('/inventory/lock',async c=>{const userId=await auth(c);if(typeof userId!=='string')return userId;const {inventoryId,isLocked}=await c.req.json().catch(()=>({}));if(!inventoryId||typeof isLocked!=='boolean')return c.json({error:'inventoryId and isLocked (boolean) required'},400);const row=await setInventoryFlag(inventoryId,userId,'locked',isLocked);if(!row)return c.json({error:'Card not found or not owned'},404);return c.json({success:true,inventoryId,isLocked});});
app.post('/inventory/favorite',async c=>{const userId=await auth(c);if(typeof userId!=='string')return userId;const {inventoryId,isFavorite}=await c.req.json().catch(()=>({}));if(!inventoryId||typeof isFavorite!=='boolean')return c.json({error:'inventoryId and isFavorite (boolean) required'},400);const row=await setInventoryFlag(inventoryId,userId,'favorite',isFavorite);if(!row)return c.json({error:'Card not found or not owned'},404);return c.json({success:true,inventoryId,isFavorite});});
app.post('/inventory/sell',async c=>{const userId=await auth(c);if(typeof userId!=='string')return userId;const {inventoryId}=await c.req.json().catch(()=>({}));if(!inventoryId)return c.json({error:'inventoryId required'},400);try{const card=await sellInventory(inventoryId,userId);if(!card)return c.json({error:'Card not found'},404);if(Number(card.sold))return c.json({error:'Card already sold'},409);const wallet=await processWalletTransaction(null,{userId,type:'sell',amount:Number(card.value||0),sourceId:inventoryId});if(!wallet.success)return c.json({error:wallet.error},400);await query('INSERT INTO transactions(id,user_id,type,amount,description,source_id) VALUES($1,$2,$3,$4,$5,$6)',[`txn_${Date.now().toString(36)}`,userId,'sell',Number(card.value||0),`Sold ${card.card_name || card.cardName || 'Card'}`,inventoryId]);return c.json({success:true,inventoryId,value:Number(card.value||0),balance:wallet.balanceAfter});}catch(e:any){return c.json({error:e.message},400);}});

app.post('/inventory/sell-all',async c=>{const userId=await auth(c);if(typeof userId!=='string')return userId;try{const cards=await query('SELECT * FROM inventory WHERE user_id=$1 AND sold=0 AND COALESCE(is_locked,locked,0)=0 FOR UPDATE',[userId]);if(!cards.length)return c.json({error:'No unlocked cards to sell'},400);const total=cards.reduce((s:any,r:any)=>s+Number(r.value||0),0);const ids=cards.map((r:any)=>r.id);await query('UPDATE inventory SET sold=1 WHERE id=ANY($1::text[])',[ids]);const wallet=await processWalletTransaction(null,{userId,type:'sell_all',amount:total,sourceId:`sellall_${ids.join('_').slice(0,80)}`});if(!wallet.success){await query('UPDATE inventory SET sold=0 WHERE id=ANY($1::text[])',[ids]);return c.json({error:wallet.error},400);}await query('INSERT INTO transactions(id,user_id,type,amount,description,source_id) VALUES($1,$2,$3,$4,$5,$6)',[`txn_${Date.now().toString(36)}`,userId,'sell_all',total,`Sold all ${cards.length} unlocked cards`,`sellall_${ids.join('_').slice(0,80)}`]);return c.json({success:true,newBalance:wallet.balanceAfter,soldCardIds:ids,totalValue:total,count:cards.length});}catch(e:any){return c.json({error:e.message},400);}});

export default app;
