import { Hono } from 'hono';
import { requireAuth } from '../lib/auth';
import { setInventoryFlag, getOwnedInventory, sellInventory } from '../repositories/inventory';
import { processWalletTransaction } from '../lib/wallet';
const app=new Hono();
async function auth(c:any){try{return await requireAuth(c);}catch(e:any){if(e.message==='ACCOUNT_DEACTIVATED')return c.json({error:'Account deactivated'},403);return c.json({error:'Authentication required'},401);}}
app.post('/inventory/lock',async c=>{const userId=await auth(c);if(typeof userId!=='string')return userId;const {inventoryId,isLocked}=await c.req.json().catch(()=>({}));if(!inventoryId||typeof isLocked!=='boolean')return c.json({error:'inventoryId and isLocked (boolean) required'},400);const row=await setInventoryFlag(inventoryId,userId,'locked',isLocked);if(!row)return c.json({error:'Card not found or not owned'},404);return c.json({success:true,inventoryId,isLocked});});
app.post('/inventory/favorite',async c=>{const userId=await auth(c);if(typeof userId!=='string')return userId;const {inventoryId,isFavorite}=await c.req.json().catch(()=>({}));if(!inventoryId||typeof isFavorite!=='boolean')return c.json({error:'inventoryId and isFavorite (boolean) required'},400);const row=await setInventoryFlag(inventoryId,userId,'favorite',isFavorite);if(!row)return c.json({error:'Card not found or not owned'},404);return c.json({success:true,inventoryId,isFavorite});});
app.post('/inventory/sell',async c=>{const userId=await auth(c);if(typeof userId!=='string')return userId;const {inventoryId}=await c.req.json().catch(()=>({}));if(!inventoryId)return c.json({error:'inventoryId required'},400);try{const card=await sellInventory(inventoryId,userId);if(!card)return c.json({error:'Card not found'},404);if(Number(card.sold))return c.json({error:'Card already sold'},409);const wallet=await processWalletTransaction(null,{userId,type:'sell',amount:Number(card.value||0),sourceId:inventoryId});if(!wallet.success)return c.json({error:wallet.error},400);return c.json({success:true,inventoryId,value:Number(card.value||0),balance:wallet.balanceAfter});}catch(e:any){return c.json({error:e.message},400);}});
export default app;
