import { Hono } from 'hono';
import { getBlinkServer, uid } from '../lib/auth';
const app = new Hono();
function safeParseJSON(raw: string, fallback: any) { try { return JSON.parse(raw); } catch { return fallback; } }
function database(c: any) { return getBlinkServer(c.env as any).db; }
app.get('/admin/logs', async c => { try { const db = database(c); const page = Math.max(1, parseInt(c.req.query('page') || '1')); const limit = Math.min(100, Math.max(1, parseInt(c.req.query('limit') || '50'))); const search = (c.req.query('search') || '').toLowerCase(); const type = c.req.query('type') || ''; const dateFrom = c.req.query('dateFrom') || ''; const dateTo = c.req.query('dateTo') || ''; const where: any = type ? { type } : undefined; let logs = await db.activityLogs.list({ where, orderBy: { createdAt: 'desc' }, limit: 2000 }) as any[]; if (search) logs = logs.filter(log => `${log.username || ''} ${log.action || ''} ${typeof log.details === 'string' ? log.details : JSON.stringify(log.details || {})}`.toLowerCase().includes(search)); if (dateFrom) { const from = new Date(dateFrom).getTime(); logs = logs.filter(log => new Date(log.createdAt).getTime() >= from); } if (dateTo) { const to = new Date(`${dateTo}T23:59:59`).getTime(); logs = logs.filter(log => new Date(log.createdAt).getTime() <= to); } return c.json({ logs: logs.slice((page - 1) * limit, page * limit), total: logs.length, page, totalPages: Math.ceil(logs.length / limit), limit }); } catch (err: any) { return c.json({ error: err.message || 'Internal server error' }, 500); } });
app.get('/admin-logs', async c => { try { const db = database(c); const userId = (c.req.query('userId') || '').trim(); const type = (c.req.query('type') || '').trim(); const limit = Math.min(200, Math.max(1, parseInt(c.req.query('limit') || '50') || 50)); const offset = Math.max(0, parseInt(c.req.query('offset') || '0') || 0); const where: any = userId ? { userId } : type ? { type } : undefined; let logs = await db.activityLogs.list({ where, orderBy: { createdAt: 'desc' }, limit: 2000 }) as any[]; if (userId && type) logs = logs.filter(log => log.type === type); return c.json({ success: true, rows: logs.slice(offset, offset + limit).map(log => ({ ...log, details: typeof log.details === 'string' ? safeParseJSON(log.details, {}) : log.details || {} })), total: logs.length }); } catch (err: any) { return c.json({ error: err.message || 'Internal server error' }, 500); } });
app.post('/admin/logs/action', async c => { try { const body = await c.req.json(); const { adminUsername, action, targetUser, details, metadata } = body; await writeLog(database(c), { type: 'admin', userId: null, username: adminUsername || 'Admin', action: action || 'Admin Action', details: { targetUser, ...details }, valueIn: 0, valueOut: 0, result: 'admin_action', metadata }); return c.json({ success: true }); } catch (err: any) { return c.json({ error: err.message }, 500); } });
export interface LogEntry { type: string; userId: string | null; username: string; action: string; details: Record<string, any>; valueIn?: number; valueOut?: number; result?: string; metadata?: Record<string, any>; }
export async function writeLog(blink: any, entry: LogEntry): Promise<void> { try { await blink.db.activityLogs.create({ id: `log_${uid()}`, type: entry.type, userId: entry.userId || null, username: entry.username || 'Unknown', action: entry.action, details: JSON.stringify(entry.details || {}), valueIn: entry.valueIn || 0, valueOut: entry.valueOut || 0, result: entry.result || null, metadata: JSON.stringify(entry.metadata || {}), createdAt: new Date().toISOString() }); } catch (err: any) { console.error('[writeLog] Failed:', err?.message || err); } }
export default app;
