import { Hono } from 'hono'; import { getBlinkServer } from '../lib/auth'; import { sha256,computeRoll } from '../lib/provablyFair';
const app=new Hono();async function user(c:any){try{const a=await getBlinkServer(c.env as any).auth.verifyToken(c.req.header('Authorization'));return a.valid&&a.userId?a.userId:null}catch{return null}}async function admin(c:any){const b=getBlinkServer(c.env as any),s=c.req.header('X-Admin-Secret');if(s&&s!=='true'){const rows=await b.db.adminCredentials.list({});if(rows.some((r:any)=>(r.adminPass||r.admin_pass)===s))return true}try{const a=await b.auth.verifyToken(c.req.header('Authorization'));if(a.valid&&a.userId){const u=await b.db.users.get(a.userId) as any;return u?.role==='admin'||u?.role==='owner'}}catch{}return false}
app.get('/provably-fair/seed-hash',async c=>{try{const r=await getBlinkServer(c.env as any).db.serverSeeds.list({where:{status:'active'},orderBy:{createdAt:'desc'},limit:1});const x=r[0] as any;return c.json({seedHash:x?.seedHash||null,activeSince:x?.periodStart||null})}catch(e:any){return c.json({error:e.message},500)}});
app.get('/provably-fair/seed-history',async c=>{try{const r=await getBlinkServer(c.env as any).db.serverSeeds.list({orderBy:{createdAt:'desc'},limit:50}) as any[];return c.json({active:r.find(x=>x.status==='active')||null,past:r.filter(x=>x.status==='revealed').map(x=>({seedHash:x.seedHash,revealedSeed:x.revealedSeed||'',periodStart:x.periodStart,periodEnd:x.periodEnd,revealedAt:x.revealedAt}))})}catch(e:any){return c.json({error:e.message},500)}});
app.get('/provably-fair/my-openings',async c=>{const id=await user(c);if(!id)return c.json({error:'Authentication required'},401);try{const rows=await getBlinkServer(c.env as any).db.packsOpened.list({where:{userId:id,provablyFair:1},orderBy:{createdAt:'desc'},limit:50});return c.json({openings:rows})}catch(e:any){return c.json({error:e.message},500)}});
app.get('/provably-fair/verify/:id',async c=>{const id=await user(c);if(!id)return c.json({error:'Authentication required'},401);try{const b=getBlinkServer(c.env as any),o=await b.db.packsOpened.get(c.req.param('id')) as any;if(!o)return c.json({error:'Opening not found'},404);if(o.userId!==id)return c.json({error:'Not your opening'},403);const seeds=await b.db.serverSeeds.list({where:{seedHash:o.serverSeedHash},limit:1}) as any[],s=seeds[0],revealed=!!s&&(!!s.revealedSeed||s.status==='revealed'),seed=revealed?s.revealedSeed:'';let roll=null,verified=false;if(revealed){roll=await computeRoll(seed,o.clientSeed,Number(o.nonce));verified=Math.abs(roll-Number(o.rollValue))<.001}return c.json({...o,isRevealed:revealed,revealedSeed:revealed?seed:undefined,recomputedRoll:roll,verified:revealed?verified:undefined})}catch(e:any){return c.json({error:e.message},500)}});
app.get('/provably-fair/my-upgrades',async c=>{const id=await user(c);if(!id)return c.json({error:'Authentication required'},401);try{return c.json({spins:await getBlinkServer(c.env as any).db.upgraderSpins.list({where:{userId:id},orderBy:{createdAt:'desc'},limit:50})})}catch(e:any){return c.json({error:e.message},500)}});
app.get('/provably-fair/verify-upgrade/:id',async c=>{const id=await user(c);if(!id)return c.json({error:'Authentication required'},401);try{const b=getBlinkServer(c.env as any),s=await b.db.upgraderSpins.get(c.req.param('id')) as any;if(!s)return c.json({error:'Upgrader spin not found'},404);if(s.userId!==id)return c.json({error:'Not your spin'},403);const seeds=await b.db.serverSeeds.list({where:{seedHash:s.serverSeedHash},limit:1}) as any[],seedRow=seeds[0],revealed=!!seedRow&&(!!seedRow.revealedSeed||seedRow.status==='revealed'),seed=revealed?seedRow.revealedSeed:'';let roll=null,verified=false;if(revealed){roll=await computeRoll(seed,s.clientSeed,Number(s.nonce));verified=Math.abs(roll-Number(s.rollValue))<.001}return c.json({...s,isRevealed:revealed,revealedSeed:revealed?seed:undefined,recomputedRoll:roll,verified:revealed?verified:undefined})}catch(e:any){return c.json({error:e.message},500)}});
export default app;
