import { Hono } from 'hono';
import { Stripe } from 'stripe';
import { getBlinkServer } from '../lib/auth';
import { query, transaction } from '../lib/postgres';
import { writeLog } from './logs';
import { processFirstDepositBonus, processReferralReward } from '../lib/payments';
import { processWalletTransactionInClient } from '../repositories/wallet';

const app = new Hono();
const getStripe=(env:any):Stripe=>{const key=env.STRIPE_SECRET_KEY||env.VITE_STRIPE_SECRET_KEY;if(!key)throw new Error('STRIPE_SECRET_KEY is not set in environment');return new Stripe(key,{apiVersion:'2023-10-16' as any});};

app.post('/create-payment-intent',async c=>{try{const body=await c.req.json().catch(()=>({}));const {amountUsd,userId}=body;let {username,email}=body;if(!amountUsd||parseFloat(amountUsd)<5)return c.json({error:'Minimum deposit is $5.00'},400);if(!userId)return c.json({error:'User ID is required'},400);const stripe=getStripe(c.env);const blink=getBlinkServer(c.env as any);const amountCents=Math.round(parseFloat(amountUsd)*100);if(!username||!email){try{const u:any=await blink.db.users.get(userId);if(u){username=username||u.username||u.displayName||'Trainer';email=email||u.email||'';}}catch{}}const safeUsername=username||'Unknown',safeEmail=email||'';let customerId:string|undefined;if(safeEmail){try{const existing=await stripe.customers.list({email:safeEmail,limit:1});if(existing.data.length){customerId=existing.data[0].id;await stripe.customers.update(existing.data[0].id,{name:safeUsername,metadata:{userId,username:safeUsername,email:safeEmail}});customerId=existing.data[0].id;}else{const customer=await stripe.customers.create({email:safeEmail,name:safeUsername,metadata:{userId,username:safeUsername,email:safeEmail}});customerId=customer.id;}}catch(e:any){console.warn('[Stripe] Customer lookup/create failed:',e.message);}}const pi=await stripe.paymentIntents.create({amount:amountCents,currency:'usd',automatic_payment_methods:{enabled:true},...(customerId?{customer:customerId}:{}),metadata:{userId,username:safeUsername,email:safeEmail,amountUsd:String(amountUsd)},description:safeEmail?`PocketPull deposit - ${safeUsername} (${safeEmail})`:`PocketPull deposit - ${safeUsername} [${userId}]`});return c.json({clientSecret:pi.client_secret,id:pi.id});}catch(e:any){return c.json({error:e.message||'Internal Server Error'},500);}});

app.post('/webhook/stripe',async c=>{const stripe=getStripe(c.env);const blink=getBlinkServer(c.env as any);const signature=c.req.header('stripe-signature'),secret=(c.env as any).STRIPE_WEBHOOK_SECRET;if(!signature||!secret)return c.text('Missing signature or secret',400);let event:Stripe.Event;try{event=await stripe.webhooks.constructEventAsync(await c.req.text(),signature,secret);}catch(e:any){return c.text(`Webhook Error: ${e.message}`,400);}if(event.type==='payment_intent.succeeded'){try{await processSuccessfulPayment(blink,event.data.object as Stripe.PaymentIntent);}catch(e:any){console.error('[Stripe Webhook]',e.message);return c.json({error:e.message},500);}}return c.json({received:true});});

app.post('/verify-deposit',async c=>{const blink=getBlinkServer(c.env as any),stripe=getStripe(c.env);try{const {paymentIntentId}=await c.req.json();if(!paymentIntentId)return c.json({error:'paymentIntentId required'},400);const pi=await stripe.paymentIntents.retrieve(paymentIntentId);if(pi.status!=='succeeded')return c.json({error:`Payment intent status: ${pi.status}`},400);return c.json({success:true,...await processSuccessfulPayment(blink,pi)});}catch(e:any){return c.json({error:e.message},500);}});

async function processSuccessfulPayment(blink:any,paymentIntent:Stripe.PaymentIntent){const meta=paymentIntent.metadata||{},userId=meta.userId,piId=paymentIntent.id;let amountUsd=meta.amountUsd;if(!amountUsd&&paymentIntent.amount)amountUsd=(paymentIntent.amount/100).toFixed(2);if(!userId||!amountUsd)return {error:'Missing critical metadata (userId or amount)'};const depositAmt=parseFloat(amountUsd);if(!Number.isFinite(depositAmt)||depositAmt<5)return {error:'Invalid deposit amount'};
const result=await transaction(async client=>{const userResult=await client.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[userId]);if(!userResult.rowCount)return {error:'User not found'};const user:any=userResult.rows[0];const txnId=`txn_stripe_${piId}`;if((await client.query('SELECT 1 FROM transactions WHERE id=$1',[txnId])).rowCount)return {status:'already_processed',newBalance:Number(user.balance||0),alreadyProcessed:true,user,username:meta.username||user.username||user.display_name||'Trainer',email:meta.email||user.email||''};const username=meta.username||user.username||user.display_name||'Trainer',email=meta.email||user.email||'';const wallet=await processWalletTransactionInClient(client,{userId,type:'deposit',amount:depositAmt,sourceId:piId,metadata:{paymentIntentId:piId}});if(!wallet.success)throw new Error(wallet.error||'Failed to credit balance');await client.query("INSERT INTO transactions(id,user_id,type,amount,description,source_id,created_at) VALUES($1,$2,'deposit',$3,$4,$5,now())",[txnId,userId,depositAmt,email?`Stripe deposit — ${depositAmt.toFixed(2)} · ${username} (${email})`:`Stripe deposit — ${depositAmt.toFixed(2)} · ${username}`,piId]);return {status:'success',newBalance:wallet.balanceAfter,user,username,email,alreadyProcessed:false};});
const u:any=result.user;if(!result.alreadyProcessed){try{await writeLog(blink,{type:'deposit',userId,username:result.username||'Trainer',action:'Stripe Deposit Confirmed',details:{amount:depositAmt,paymentIntentId:piId,paymentMethod:'Stripe',status:'completed',email:result.email||''},valueIn:depositAmt,valueOut:0,result:'success'});}catch(e){console.warn('[Stripe] Activity log failed',e);}}
if(Number(u.first_deposit_bonus_paid||0)===0)await processFirstDepositBonus(blink,userId,depositAmt);if(depositAmt>=5&&u.referred_by_id&&!Number(u.referral_reward_paid||0))await processReferralReward(blink,userId,u.referred_by_id,depositAmt);return {status:'success',newBalance:result.newBalance};}

export default app;
