import { Hono } from 'hono';
import { requireAuth } from '../lib/auth';
import { getDb } from '../db/client';
import { getUserProfile } from '../db/repositories/users';
import { uid } from '../lib/auth';

const app=new Hono();
const mapMessage=(r:any)=>({id:r.id,chatId:r.chat_id,userId:r.user_id,senderType:r.sender_type,message:r.message,createdAt:r.created_at});
const mapChat=(r:any)=>({id:r.id,userId:r.user_id,username:r.username||'Trainer',status:r.status,subject:r.subject||'',lastMessage:r.last_message||'',lastMessageAt:r.last_message_at||r.created_at,createdAt:r.created_at,updatedAt:r.updated_at||r.created_at});
async function admin(c:any){const id=await requireAuth(c);const user=await getUserProfile(c.env as any,id);if(!user||!['admin','owner'].includes(user.role))throw new Error('ADMIN_REQUIRED');return id;}

app.get('/support/chat',async c=>{try{const userId=await requireAuth(c);const result=await getDb(c.env as any).query(`SELECT * FROM support_chats WHERE user_id=$1 AND status<>'archived' ORDER BY created_at DESC LIMIT 1`,[userId]);return c.json({chat:result.rows[0]?mapChat(result.rows[0]):null});}catch(err:any){return c.json({error:err?.message||'Unauthorized'},401);}});
app.get('/support/messages',async c=>{try{const userId=await requireAuth(c);const chatId=c.req.query('chatId');if(!chatId)return c.json({error:'chatId required'},400);const owned=await getDb(c.env as any).query('SELECT 1 FROM support_chats WHERE id=$1 AND user_id=$2 LIMIT 1',[chatId,userId]);if(!owned.rows.length)return c.json({error:'Not your chat'},403);const rows=await getDb(c.env as any).query(`SELECT * FROM support_messages WHERE chat_id=$1 ORDER BY created_at ASC LIMIT 200`,[chatId]);return c.json({messages:rows.rows.map(mapMessage)});}catch(err:any){return c.json({error:err?.message||'Failed to load messages'},500);}});
app.post('/support/send',async c=>{try{const userId=await requireAuth(c);const body=await c.req.json();const text=String(body.message||'').trim();if(!text)return c.json({error:'Message required'},400);const db=getDb(c.env as any);let chatId=body.chatId;const client=await db.connect();try{await client.query('BEGIN');if(chatId){const own=await client.query('SELECT * FROM support_chats WHERE id=$1 AND user_id=$2 FOR UPDATE',[chatId,userId]);if(!own.rows.length)throw new Error('Not your chat');}else{const existing=await client.query(`SELECT * FROM support_chats WHERE user_id=$1 AND status<>'archived' ORDER BY created_at DESC LIMIT 1 FOR UPDATE`,[userId]);if(existing.rows[0])chatId=existing.rows[0].id;else{chatId=`chat_${uid()}`;const user=await getUserProfile(c.env as any,userId);await client.query(`INSERT INTO support_chats (id,user_id,username,status,subject,last_message,last_message_at,created_at,updated_at) VALUES ($1,$2,$3,'pending',$4,$5,NOW(),NOW(),NOW())`,[chatId,user?.username||user?.displayName||'Trainer',text.slice(0,80),text]);}}const messageId=`msg_${uid()}`;await client.query(`INSERT INTO support_messages (id,chat_id,user_id,sender_type,message,created_at) VALUES ($1,$2,$3,'user',$4,NOW())`,[messageId,chatId,userId,text]);await client.query(`UPDATE support_chats SET last_message=$2,last_message_at=NOW(),updated_at=NOW(),status=CASE WHEN status='completed' THEN 'active' ELSE status END WHERE id=$1`,[chatId,text]);await client.query('COMMIT');return c.json({success:true,message:{id:messageId,chatId,userId,senderType:'user',message:text,createdAt:new Date().toISOString()}});}catch(err){await client.query('ROLLBACK');throw err;}finally{client.release();}}catch(err:any){return c.json({error:err?.message||'Failed to send message'},500);}});

app.get('/admin/support/chats',async c=>{try{await admin(c);const rows=await getDb(c.env as any).query(`SELECT * FROM support_chats ORDER BY last_message_at DESC NULLS LAST LIMIT 200`);return c.json({chats:rows.rows.map(mapChat)});}catch(err:any){return c.json({error:err?.message||'Unauthorized'},err?.message==='ADMIN_REQUIRED'?403:401);}});
app.get('/admin/support/messages',async c=>{try{await admin(c);const chatId=c.req.query('chatId');if(!chatId)return c.json({error:'chatId required'},400);const rows=await getDb(c.env as any).query(`SELECT * FROM support_messages WHERE chat_id=$1 ORDER BY created_at ASC LIMIT 200`,[chatId]);return c.json({messages:rows.rows.map(mapMessage)});}catch(err:any){return c.json({error:err?.message||'Failed to load messages'},500);}});
app.post('/admin/support/reply',async c=>{try{const adminId=await admin(c);const body=await c.req.json();const chatId=String(body.chatId||'');const text=String(body.message||'').trim();if(!chatId||!text)return c.json({error:'chatId and message required'},400);const client=await getDb(c.env as any).connect();try{await client.query('BEGIN');const exists=await client.query('SELECT 1 FROM support_chats WHERE id=$1 FOR UPDATE',[chatId]);if(!exists.rows.length)throw new Error('Chat not found');const id=`msg_${uid()}`;await client.query(`INSERT INTO support_messages (id,chat_id,user_id,sender_type,message,created_at) VALUES ($1,$2,$3,'admin',$4,NOW())`,[id,chatId,adminId,text]);await client.query(`UPDATE support_chats SET last_message=$2,last_message_at=NOW(),updated_at=NOW(),status='active' WHERE id=$1`,[chatId,text]);await client.query('COMMIT');return c.json({success:true,message:{id,chatId,userId:adminId,senderType:'admin',message:text,createdAt:new Date().toISOString()}});}catch(err){await client.query('ROLLBACK');throw err;}finally{client.release();}}catch(err:any){return c.json({error:err?.message||'Failed to send reply'},err?.message==='ADMIN_REQUIRED'?403:500);}});
app.post('/admin/support/status',async c=>{try{await admin(c);const body=await c.req.json();if(!body.chatId||!body.status)return c.json({error:'chatId and status required'},400);if(!['pending','active','completed','archived'].includes(body.status))return c.json({error:'Invalid status'},400);await getDb(c.env as any).query('UPDATE support_chats SET status=$2,updated_at=NOW() WHERE id=$1',[body.chatId,body.status]);return c.json({success:true});}catch(err:any){return c.json({error:err?.message||'Failed to update status'},500);}});
export default app;
