import { mkdir, writeFile } from 'node:fs/promises';
import { createClient } from '@blinkdotnew/sdk';
import { IMPORT_ORDER } from './exportFormat';

const projectId=process.env.BLINK_PROJECT_ID,secretKey=process.env.BLINK_SECRET_KEY;
if(!projectId||!secretKey)throw new Error('BLINK_PROJECT_ID and BLINK_SECRET_KEY are required');
const TABLE_TO_SDK:Record<string,string>={users:'users',packs_catalog:'packsCatalog',pack_cards:'packCards',inventory:'inventory',transactions:'transactions',packs_opened:'packsOpened',server_seeds:'serverSeeds',pack_odds_versions:'packOddsVersions',user_nonces:'userNonces',pack_cooldowns:'packCooldowns',admin_credentials:'adminCredentials',upgrader_multiplier_settings:'upgraderMultiplierSettings',upgrader_spins:'upgraderSpins',battles:'battles',battle_players:'battlePlayers',battle_participants:'battleParticipants',battle_results:'battleResults',battle_pull_audits:'battlePullAudits',upgrader_settings:'upgraderSettings',upgrader_history:'upgraderHistory',exchanger_activity:'exchangerActivity',cashout_requests:'cashoutRequests',cashouts:'cashouts',activity_logs:'activityLogs',outbound_emails:'outboundEmails',wallet_transactions:'walletTransactions',leaderboard_stats:'leaderboardStats'};
const PAGE_SIZE=1000;
async function exportTable(blink:any,sdkName:string){const all:any[]=[];for(let offset=0;;offset+=PAGE_SIZE){const rows=await blink.db[sdkName].list({limit:PAGE_SIZE,offset});if(!rows?.length)break;all.push(...rows);console.log(`  ${sdkName}: ${all.length}`);if(rows.length<PAGE_SIZE)break;}return all;}
async function main(){const blink:any=createClient({projectId,secretKey}),output:any={};for(const table of IMPORT_ORDER){const sdkName=TABLE_TO_SDK[table];if(!sdkName)continue;try{output[table]=await exportTable(blink,sdkName);console.log(`${table}: exported ${output[table].length}`);}catch(error:any){console.warn(`${table}: export failed (${error?.message||error})`);output[table]=[];}}await mkdir('backend/db/import/exports',{recursive:true});const path=process.argv[2]||'backend/db/import/exports/blink-export.json';await writeFile(path,JSON.stringify(output,null,2),'utf8');console.log(`Wrote ${path}`);}
main().catch(error=>{console.error(error);process.exit(1);});
