-- PocketPull PostgreSQL migration 001
-- Provider-agnostic PostgreSQL 14+ schema. Review and back up before production cutover.
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT,username TEXT,display_name TEXT,role TEXT NOT NULL DEFAULT 'user',balance NUMERIC(18,2) NOT NULL DEFAULT 0,matched_balance NUMERIC(18,2) NOT NULL DEFAULT 0,is_deleted INTEGER NOT NULL DEFAULT 0,is_banned INTEGER NOT NULL DEFAULT 0,is_bot INTEGER NOT NULL DEFAULT 0,referral_code TEXT,referred_by_id TEXT,referral_reward_paid INTEGER NOT NULL DEFAULT 0,first_deposit_bonus_paid INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_users_referred_by ON users(referred_by_id); CREATE INDEX IF NOT EXISTS idx_users_email ON users(email); CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_active ON users(username) WHERE is_deleted = 0 AND username IS NOT NULL;
CREATE TABLE IF NOT EXISTS packs_catalog (id TEXT PRIMARY KEY,name TEXT,price NUMERIC(18,2) NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,pack_type TEXT NOT NULL DEFAULT 'standard',quantity_limit INTEGER NOT NULL DEFAULT 0,current_quantity INTEGER NOT NULL DEFAULT 0,cooldown_hours NUMERIC(10,2) NOT NULL DEFAULT 0,expires_at TIMESTAMPTZ,image_url TEXT,description TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS idx_packs_catalog_active ON packs_catalog(is_active);
CREATE TABLE IF NOT EXISTS pack_cards (id TEXT PRIMARY KEY,pack_id TEXT NOT NULL REFERENCES packs_catalog(id) ON DELETE CASCADE,card_name TEXT NOT NULL,rarity TEXT NOT NULL DEFAULT 'common',estimated_value NUMERIC(18,2) NOT NULL DEFAULT 0,card_image_url TEXT,pull_chance NUMERIC(12,8),quantity INTEGER NOT NULL DEFAULT 0,sort_order INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS idx_pack_cards_pack_id ON pack_cards(pack_id);
CREATE TABLE IF NOT EXISTS pack_cooldowns (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,pack_id TEXT NOT NULL REFERENCES packs_catalog(id) ON DELETE CASCADE,last_opened_at TIMESTAMPTZ NOT NULL,UNIQUE(user_id,pack_id));
CREATE TABLE IF NOT EXISTS inventory (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,card_id TEXT,card_name TEXT NOT NULL,rarity TEXT,value NUMERIC(18,2) NOT NULL DEFAULT 0,emoji TEXT,is_favorite INTEGER NOT NULL DEFAULT 0,is_locked INTEGER NOT NULL DEFAULT 0,card_image_url TEXT,pack_name TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS idx_inventory_user_id ON inventory(user_id); CREATE INDEX IF NOT EXISTS idx_inventory_user_locked ON inventory(user_id,is_locked);
CREATE TABLE IF NOT EXISTS transactions (id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id) ON DELETE SET NULL,type TEXT NOT NULL,amount NUMERIC(18,2) NOT NULL DEFAULT 0,description TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS idx_transactions_user_created ON transactions(user_id,created_at DESC); CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(type);
CREATE TABLE IF NOT EXISTS wallet_transactions (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL,amount NUMERIC(18,2) NOT NULL,balance_before NUMERIC(18,2) NOT NULL,balance_after NUMERIC(18,2) NOT NULL,matched_before NUMERIC(18,2) NOT NULL,matched_after NUMERIC(18,2) NOT NULL,source_id TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,type,source_id)); CREATE INDEX IF NOT EXISTS idx_wallet_transactions_user_created ON wallet_transactions(user_id,created_at DESC); CREATE INDEX IF NOT EXISTS idx_wallet_transactions_source ON wallet_transactions(source_id);
CREATE TABLE IF NOT EXISTS server_seeds (id TEXT PRIMARY KEY,seed_hash TEXT NOT NULL,status TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),revealed_at TIMESTAMPTZ); CREATE INDEX IF NOT EXISTS idx_server_seeds_status_created ON server_seeds(status,created_at DESC);
CREATE TABLE IF NOT EXISTS user_nonces (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,pack_nonce BIGINT NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS pack_odds_versions (content_hash TEXT PRIMARY KEY,pack_id TEXT NOT NULL REFERENCES packs_catalog(id) ON DELETE CASCADE,odds_json JSONB NOT NULL,card_count INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS idx_pack_odds_versions_pack ON pack_odds_versions(pack_id,created_at DESC);
CREATE TABLE IF NOT EXISTS packs_opened (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,pack_id TEXT NOT NULL REFERENCES packs_catalog(id) ON DELETE RESTRICT,pack_name TEXT,cost NUMERIC(18,2) NOT NULL DEFAULT 0,card_name TEXT,rarity TEXT,client_seed TEXT,nonce BIGINT,roll_value NUMERIC(20,12),server_seed_hash TEXT,odds_version_hash TEXT,provably_fair INTEGER NOT NULL DEFAULT 1,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS idx_packs_opened_user_created ON packs_opened(user_id,created_at DESC); CREATE INDEX IF NOT EXISTS idx_packs_opened_pack_created ON packs_opened(pack_id,created_at DESC);
CREATE TABLE IF NOT EXISTS activity_logs (id TEXT PRIMARY KEY,type TEXT NOT NULL,user_id TEXT REFERENCES users(id) ON DELETE SET NULL,username TEXT,action TEXT,details JSONB NOT NULL DEFAULT '{}'::jsonb,value_in NUMERIC(18,2) NOT NULL DEFAULT 0,value_out NUMERIC(18,2) NOT NULL DEFAULT 0,result TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS idx_activity_logs_created ON activity_logs(created_at DESC); CREATE INDEX IF NOT EXISTS idx_activity_logs_user_created ON activity_logs(user_id,created_at DESC); CREATE INDEX IF NOT EXISTS idx_activity_logs_type_created ON activity_logs(type,created_at DESC);
CREATE TABLE IF NOT EXISTS admin_credentials (id TEXT PRIMARY KEY,admin_pass TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS upgrader_multiplier_settings (multiplier NUMERIC(12,4) PRIMARY KEY,max_chance NUMERIC(8,4) NOT NULL DEFAULT 75,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
