CREATE TABLE IF NOT EXISTS cashout_requests (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,username TEXT,confirmation_number TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'pending',total_value NUMERIC(18,2) NOT NULL DEFAULT 0,total_cards INTEGER NOT NULL DEFAULT 0,cards_json JSONB NOT NULL DEFAULT '[]'::jsonb,shipping_name TEXT,shipping_address TEXT,shipping_city TEXT,shipping_state TEXT,shipping_zip TEXT,shipping_country TEXT DEFAULT 'US',notes TEXT,id_image_url TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE cashout_requests ADD COLUMN IF NOT EXISTS fulfilled_card_ids JSONB NOT NULL DEFAULT '[]'::jsonb; ALTER TABLE cashout_requests ADD COLUMN IF NOT EXISTS tracking_number TEXT; ALTER TABLE cashout_requests ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS idx_cashout_requests_user_created ON cashout_requests(user_id,created_at DESC); CREATE INDEX IF NOT EXISTS idx_cashout_requests_status_created ON cashout_requests(status,created_at DESC);
CREATE TABLE IF NOT EXISTS outbound_emails (id TEXT PRIMARY KEY,recipient TEXT,sender TEXT,subject TEXT,email_type TEXT,sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),cashout_id TEXT REFERENCES cashout_requests(id) ON DELETE SET NULL,text_content TEXT,html_content TEXT,status TEXT NOT NULL,provider_message_id TEXT,error_message TEXT); CREATE INDEX IF NOT EXISTS idx_outbound_emails_sent_at ON outbound_emails(sent_at DESC); CREATE INDEX IF NOT EXISTS idx_outbound_emails_cashout ON outbound_emails(cashout_id);
CREATE TABLE IF NOT EXISTS battles (id TEXT PRIMARY KEY,host_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,host_username TEXT,host_avatar TEXT,mode TEXT NOT NULL DEFAULT 'standard',player_count INTEGER NOT NULL DEFAULT 2,team_mode INTEGER NOT NULL DEFAULT 0,is_public INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'waiting',packs_json TEXT NOT NULL DEFAULT '[]',total_cost NUMERIC(18,2) NOT NULL DEFAULT 0,private_code TEXT,player_count_current INTEGER NOT NULL DEFAULT 0,started_at TIMESTAMPTZ,ended_at TIMESTAMPTZ,is_spinning INTEGER NOT NULL DEFAULT 0,winner_user_id TEXT,winner_username TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_battles_status_public_created ON battles(status,is_public,created_at DESC); CREATE INDEX IF NOT EXISTS idx_battles_host ON battles(host_user_id,created_at DESC); CREATE UNIQUE INDEX IF NOT EXISTS idx_battles_private_code ON battles(private_code) WHERE private_code IS NOT NULL;
CREATE TABLE IF NOT EXISTS battle_players (id TEXT PRIMARY KEY,battle_id TEXT NOT NULL REFERENCES battles(id) ON DELETE CASCADE,user_id TEXT NOT NULL,username TEXT,avatar TEXT,is_ai INTEGER NOT NULL DEFAULT 0,team_side TEXT,cards_json TEXT NOT NULL DEFAULT '[]',total_value NUMERIC(18,2) NOT NULL DEFAULT 0,is_winner INTEGER NOT NULL DEFAULT 0,joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(battle_id,user_id)); CREATE INDEX IF NOT EXISTS idx_battle_players_battle ON battle_players(battle_id,joined_at); CREATE INDEX IF NOT EXISTS idx_battle_players_user ON battle_players(user_id,joined_at DESC);
CREATE TABLE IF NOT EXISTS battle_pull_audits (id TEXT PRIMARY KEY,battle_id TEXT NOT NULL REFERENCES battles(id) ON DELETE CASCADE,battle_player_id TEXT NOT NULL REFERENCES battle_players(id) ON DELETE CASCADE,user_id TEXT NOT NULL,pack_id TEXT NOT NULL REFERENCES packs_catalog(id) ON DELETE RESTRICT,pack_name TEXT,card_name TEXT,rarity TEXT,cost NUMERIC(18,2) NOT NULL DEFAULT 0,client_seed TEXT NOT NULL,nonce BIGINT NOT NULL,roll_value NUMERIC(20,12) NOT NULL,server_seed_hash TEXT NOT NULL,odds_version_hash TEXT,is_bot INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS idx_battle_pull_audits_battle ON battle_pull_audits(battle_id,created_at); CREATE INDEX IF NOT EXISTS idx_battle_pull_audits_user ON battle_pull_audits(user_id,created_at DESC);
ALTER TABLE packs_catalog ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0; ALTER TABLE packs_catalog ADD COLUMN IF NOT EXISTS glow_color TEXT; ALTER TABLE packs_catalog ADD COLUMN IF NOT EXISTS border_color TEXT; ALTER TABLE packs_catalog ADD COLUMN IF NOT EXISTS name_color TEXT; ALTER TABLE packs_catalog ADD COLUMN IF NOT EXISTS description_color TEXT; ALTER TABLE packs_catalog ADD COLUMN IF NOT EXISTS price_color TEXT; ALTER TABLE packs_catalog ADD COLUMN IF NOT EXISTS button_text_color TEXT; ALTER TABLE packs_catalog ADD COLUMN IF NOT EXISTS open_another_button_text_color TEXT; ALTER TABLE pack_cards ADD COLUMN IF NOT EXISTS original_quantity INTEGER NOT NULL DEFAULT 0;
