import { getDb, type DbEnv } from './client';

const TABLES:Record<string,string>={users:'users',packsCatalog:'packs_catalog',packCards:'pack_cards',packCooldowns:'pack_cooldowns',inventory:'inventory',transactions:'transactions',walletTransactions:'wallet_transactions',leaderboardStats:'leaderboard_stats',supportChats:'support_chats',supportMessages:'support_messages',cashoutRequests:'cashout_requests',outboundEmails:'outbound_emails',activityLogs:'activity_logs',upgraderMultiplierSettings:'upgrader_multiplier_settings',adminCredentials:'admin_credentials',serverSeeds:'server_seeds',packOddsVersions:'pack_odds_versions',packsOpened:'packs_opened',upgraderSpins:'upgrader_spins',exchangerTrades:'exchanger_trades',battles:'battles',battlePlayers:'battle_players',userNonces:'user_nonces',battlePullAudits:'battle_pull_audits'};
const snake=(s:string)=>s.replace(/[A-Z]/g,m=>`_${m.toLowerCase()}`);const camel=(s:string)=>s.replace(/_([a-z])/g,(_,c)=>c.toUpperCase());const mapRow=(row:any)=>Object.fromEntries(Object.entries(row).map(([k,v])=>[camel(k),v]));
const tableFor=(collection:string)=>{const table=TABLES[collection];if(!table)throw new Error(`PostgreSQL compatibility collection not supported: ${collection}`);return table;};
function normalize(v:any){return v;}
function buildWhere(where:any,bind:(v:any)=>string){const parts:string[]=[];for(const [rawKey,rawValue] of Object.entries(where||{})){const key=snake(rawKey);if(rawValue&&typeof rawValue==='object'&&!Array.isArray(rawValue)){if('in'in rawValue){const arr=Array.isArray((rawValue as any).in)?(rawValue as any).in:[];parts.push(`"${key}" = ANY(${bind(arr)}::text[])`);continue;}for(const [op,value] of Object.entries(rawValue as any)){const symbol=op==='gte'?'>=':op==='lte'?'<=':op==='gt'?'>':op==='lt'?'<':op==='neq'?'<>' :op==='contains'?'ILIKE':'=';parts.push(`"${key}" ${symbol} ${bind(op==='contains'?`%${value}%`:value)}`);}}else parts.push(`"${key}" = ${bind(normalize(rawValue))}`);}return parts.length?`WHERE ${parts.join(' AND ')}`:'';}
function collection(env:DbEnv,name:string){const table=tableFor(name);return {
 async list(options:any={}){const values:any[]=[];const bind=(v:any)=>{values.push(v);return `$${values.length}`;};const where=buildWhere(options.where,bind);const order=Object.entries(options.orderBy||{}).map(([k,v])=>`"${snake(k)}" ${String(v).toUpperCase()==='DESC'?'DESC':'ASC'}`).join(', ')||'created_at DESC';const limit=Math.min(1000,Number(options.limit||1000));const offset=Math.max(0,Number(options.offset||0));const r=await getDb(env).query(`SELECT * FROM "${table}" ${where} ORDER BY ${order} LIMIT ${bind(limit)} OFFSET ${bind(offset)}`,values);return r.rows.map(mapRow);},
 async get(id:string){const r=await getDb(env).query(`SELECT * FROM "${table}" WHERE id=$1 LIMIT 1`,[id]);return r.rows[0]?mapRow(r.rows[0]):null;},
 async create(data:any){const pairs=Object.entries(data).map(([k,v])=>[snake(k),v] as const);const r=await getDb(env).query(`INSERT INTO "${table}" (${pairs.map(p=>`"${p[0]}"`).join(',')}) VALUES (${pairs.map((_,i)=>`$${i+1}`).join(',')}) RETURNING *`,pairs.map(p=>p[1]));return mapRow(r.rows[0]);},
 async createMany(rows:any[]){const client=await getDb(env).connect();try{await client.query('BEGIN');const out:any[]=[];for(const data of rows){const pairs=Object.entries(data).map(([k,v])=>[snake(k),v] as const);const r=await client.query(`INSERT INTO "${table}" (${pairs.map(p=>`"${p[0]}"`).join(',')}) VALUES (${pairs.map((_,i)=>`$${i+1}`).join(',')}) RETURNING *`,pairs.map(p=>p[1]));out.push(mapRow(r.rows[0]));}await client.query('COMMIT');return out;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}},
 async update(id:string,data:any){const pairs=Object.entries(data).map(([k,v])=>[snake(k),v] as const);const r=await getDb(env).query(`UPDATE "${table}" SET ${pairs.map(([k],i)=>`"${k}"=$${i+1}`).join(',')} WHERE id=$${pairs.length+1} RETURNING *`,[...pairs.map(p=>p[1]),id]);return r.rows[0]?mapRow(r.rows[0]):null;},
 async updateMany(options:any,data?:any){const where=options?.where||{};const payload=data||options?.data||{};const values:any[]=[];const bind=(v:any)=>{values.push(v);return `$${values.length}`;};const sets=Object.entries(payload).map(([k,v])=>`"${snake(k)}"=${bind(v)}`).join(',');const clause=buildWhere(where,bind);const r=await getDb(env).query(`UPDATE "${table}" SET ${sets} ${clause}`,values);return {count:r.rowCount||0};},
 async delete(id:string){await getDb(env).query(`DELETE FROM "${table}" WHERE id=$1`,[id]);return {success:true};},
 async count(options:any={}){const values:any[]=[];const bind=(v:any)=>{values.push(v);return `$${values.length}`;};const where=buildWhere(options.where,bind);const r=await getDb(env).query<{count:string}>(`SELECT COUNT(*)::text AS count FROM "${table}" ${where}`,values);return Number(r.rows[0]?.count||0);},
 async exists(options:any={}){const values:any[]=[];const bind=(v:any)=>{values.push(v);return `$${values.length}`;};const where=buildWhere(options.where,bind);const r=await getDb(env).query(`SELECT 1 FROM "${table}" ${where} LIMIT 1`,values);return r.rows.length>0;},
 async upsert(data:any){const pairs=Object.entries(data).map(([k,v])=>[snake(k),v] as const);const conflict=pairs.some(p=>p[0]==='id')?'id':name==='upgraderMultiplierSettings'&&pairs.some(p=>p[0]==='multiplier')?'multiplier':null;const values=pairs.map(p=>p[1]);let sql=`INSERT INTO "${table}" (${pairs.map(p=>`"${p[0]}"`).join(',')}) VALUES (${pairs.map((_,i)=>`$${i+1}`).join(',')})`;if(conflict){const updates=pairs.filter(p=>p[0]!==conflict).map(p=>`"${p[0]}"=EXCLUDED."${p[0]}"`);sql+=updates.length?` ON CONFLICT ("${conflict}") DO UPDATE SET ${updates.join(',')}`:' ON CONFLICT DO NOTHING';}const r=await getDb(env).query(sql+' RETURNING *',values);return r.rows[0]?mapRow(r.rows[0]):null;}
};}
export function createBlinkDbCompat(env:DbEnv){return new Proxy({}, {get(_target,property:string){if(property==='table')return(name:string)=>collection(env,name);if(property==='sql')return async(text:string,values:any[]=[])=>(await getDb(env).query(text.replace(/\?/g,()=>`$${values.indexOf(values.shift?.())+1}`),values));return collection(env,property);}});}
