import { useQuery } from '@tanstack/react-query';
import { blink } from '../lib/blink';
import { formatDistanceToNow } from 'date-fns';

const BACKEND_BASE = import.meta.env.VITE_BACKEND_URL || 'https://b2nnhe2n.backend.blink.new';
async function publicApi(path: string) { const res = await fetch(`${BACKEND_BASE}${path}`); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data?.error || `API error ${res.status}`); return data; }
async function authApi(path: string) { const token = await blink.auth.getValidToken(); const res = await fetch(`${BACKEND_BASE}${path}`, { headers: { Authorization: `Bearer ${token}` } }); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data?.error || `API error ${res.status}`); return data; }

export interface PackCatalog { id: string; packType: 'standard' | 'mystery'; name: string; price: number; description: string; imageUrl: string; glowColor: string; borderColor: string; isActive: number; sortOrder: number; quantityLimit: number; currentQuantity: number; cooldownHours: number; expiresAt: string | null; nameColor?: string; descriptionColor?: string; priceColor?: string; buttonTextColor?: string; openAnotherButtonTextColor?: string; }
export interface PackCard { id: string; packId: string; cardName: string; rarity: 'common' | 'uncommon' | 'rare' | 'ultra' | 'secret' | 'god'; pullChance: number; estimatedValue: number; cardImageUrl?: string; sortOrder: number; quantity?: number; originalQuantity?: number; }
export interface PackCooldown { id: string; userId: string; packId: string; lastOpenedAt: string; }

export function usePacks() { return useQuery<PackCatalog[]>({ queryKey: ['packs-catalog'], queryFn: async () => { const { packs } = await publicApi('/catalog/packs'); return packs as PackCatalog[]; }, staleTime: 60_000, refetchInterval: 60_000, refetchIntervalInBackground: false, refetchOnMount: 'always', refetchOnReconnect: true, retry: 6, retryDelay: attempt => Math.min(1500 * 2 ** attempt, 15000) }); }
export function useUserCooldowns(userId: string | undefined) { return useQuery<Record<string, string>>({ queryKey: ['user-pack-cooldowns', userId], enabled: !!userId, queryFn: async () => { const { cooldowns } = await authApi('/catalog/cooldowns'); return Object.fromEntries((cooldowns as any[]).map(r => [r.packId, r.lastOpenedAt])); }, staleTime: 20_000, refetchInterval: 20_000 }); }
export function usePackCards(packId: string | null) { return useQuery<PackCard[]>({ queryKey: ['pack-cards', packId], enabled: !!packId, queryFn: async () => { const { cards } = await publicApi(`/catalog/packs/${encodeURIComponent(packId!)}/cards`); return cards as PackCard[]; }, staleTime: 10 * 60 * 1000 }); }
export function useAllCards() { return useQuery<PackCard[]>({ queryKey: ['all-pack-cards'], queryFn: async () => { const { cards } = await publicApi('/catalog/all-cards'); return cards as PackCard[]; }, staleTime: 15 * 60 * 1000, refetchIntervalInBackground: false, refetchOnMount: 'always', refetchOnReconnect: true, retry: 3, retryDelay: attempt => Math.min(1000 * 2 ** attempt, 8000) }); }
export function useRecentPulls(limit = 12) { return useQuery({ queryKey: ['recent-pulls', limit], queryFn: async () => { const { pulls } = await publicApi(`/catalog/recent-pulls?limit=${encodeURIComponent(limit)}`); return (pulls as any[]).map(p => ({ ...p, time: p.time || (p.createdAt ? formatDistanceToNow(new Date(p.createdAt), { addSuffix: true }) : '') })); }, staleTime: 30_000, refetchIntervalInBackground: false, refetchOnMount: 'always', refetchOnReconnect: true, retry: 6, retryDelay: attempt => Math.min(1500 * 2 ** attempt, 15000) }); }
export function useHallOfFame(limit = 5) { return useQuery({ queryKey: ['hall-of-fame', limit], queryFn: async () => { const { pulls } = await publicApi(`/catalog/hall-of-fame?limit=${encodeURIComponent(limit)}`); return pulls; }, staleTime: 60_000, refetchIntervalInBackground: false, refetchOnMount: 'always', refetchOnReconnect: true, retry: 6, retryDelay: attempt => Math.min(1500 * 2 ** attempt, 15000) }); }
export function useGodPulls() { return useQuery({ queryKey: ['god-pulls-catalog'], queryFn: async () => { const { cards } = await publicApi('/catalog/god-pulls'); return cards; }, staleTime: 600_000, refetchIntervalInBackground: false, refetchOnMount: 'always', refetchOnReconnect: true, retry: 6, retryDelay: attempt => Math.min(1500 * 2 ** attempt, 15000) }); }
