import { useQuery } from '@tanstack/react-query';
import { blink } from '../lib/blink';
import { formatDistanceToNow } from 'date-fns';

export interface PackCatalog { id: string; packType: 'standard' | 'mystery'; name: string; price: number; description: string; imageUrl: string; glowColor: string; borderColor: string; isActive: number; sortOrder: number; quantityLimit: number; currentQuantity: number; cooldownHours: number; expiresAt: string | null; nameColor?: string; descriptionColor?: string; priceColor?: string; buttonTextColor?: string; openAnotherButtonTextColor?: string; }
export interface PackCard { id: string; packId: string; cardName: string; rarity: 'common' | 'uncommon' | 'rare' | 'ultra' | 'secret' | 'god'; pullChance: number; estimatedValue: number; cardImageUrl?: string; sortOrder: number; quantity?: number; originalQuantity?: number; packName?: string; }
export interface PackCooldown { id: string; userId: string; packId: string; lastOpenedAt: string; }

const BACKEND_BASE = import.meta.env.VITE_BACKEND_URL || 'https://b2nnhe2n.backend.blink.new';
async function request<T>(path: string, authenticated = false): Promise<T> { const token = authenticated ? await blink.auth.getValidToken().catch(() => null) : null; const res = await fetch(`${BACKEND_BASE}${path}`, { headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}) } }); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data?.error || `API error ${res.status}`); return data as T; }
function normalizePack(r: any): PackCatalog { return { ...r, packType: r.packType === 'mystery' ? 'mystery' : 'standard', price: Number(r.price), sortOrder: Number(r.sortOrder ?? 0), isActive: Number(r.isActive ?? 1), quantityLimit: Number(r.quantityLimit ?? 0), currentQuantity: Number(r.currentQuantity ?? 0), cooldownHours: Number(r.cooldownHours ?? 0), expiresAt: r.expiresAt || null, nameColor: r.nameColor || '#ffffff', descriptionColor: r.descriptionColor || '#ffffff', priceColor: r.priceColor || '#ffffff', buttonTextColor: r.buttonTextColor || '#ffffff', openAnotherButtonTextColor: r.openAnotherButtonTextColor || r.buttonTextColor || '#ffffff' }; }
function normalizeCard(r: any): PackCard { return { ...r, pullChance: Number(r.pullChance ?? 0), estimatedValue: Number(r.estimatedValue ?? 0), sortOrder: Number(r.sortOrder ?? 0), quantity: Number(r.quantity ?? 0), originalQuantity: Number(r.originalQuantity ?? r.quantity ?? 0) }; }

export function usePacks() { return useQuery<PackCatalog[]>({ queryKey: ['packs-catalog'], queryFn: async () => { const data = await request<{ packs: any[] }>('/catalog/packs'); if (!Array.isArray(data.packs)) throw new Error('Invalid packs response'); return data.packs.map(normalizePack); }, staleTime: 60_000, refetchInterval: 60_000, refetchIntervalInBackground: false, refetchOnMount: 'always', refetchOnReconnect: true, retry: 6, retryDelay: attempt => Math.min(1500 * 2 ** attempt, 15000) }); }
export function useUserCooldowns(userId: string | undefined) { return useQuery<Record<string, string>>({ queryKey: ['user-pack-cooldowns', userId], enabled: !!userId, queryFn: async () => { const data = await request<{ cooldowns: PackCooldown[] }>('/catalog/cooldowns', true); return Object.fromEntries((data.cooldowns || []).map(r => [r.packId, r.lastOpenedAt])); }, staleTime: 20_000, refetchInterval: 20_000 }); }
export function usePackCards(packId: string | null) { return useQuery<PackCard[]>({ queryKey: ['pack-cards', packId], enabled: !!packId, queryFn: async () => { const data = await request<{ cards: any[] }>(`/catalog/packs/${encodeURIComponent(packId!)}/cards`); return (data.cards || []).map(normalizeCard); }, staleTime: 10 * 60 * 1000 }); }
export function useAllCards() { return useQuery<PackCard[]>({ queryKey: ['all-pack-cards'], queryFn: async () => { const data = await request<{ cards: any[] }>('/catalog/all-cards'); return (data.cards || []).map(normalizeCard); }, staleTime: 15 * 60 * 1000, refetchIntervalInBackground: false, refetchOnMount: 'always', refetchOnReconnect: true, retry: 3, retryDelay: attempt => Math.min(1000 * 2 ** attempt, 8000) }); }
export function useRecentPulls(limit = 12) { return useQuery({ queryKey: ['recent-pulls', limit], queryFn: async () => { const data = await request<{ pulls: any[] }>(`/catalog/recent-pulls?limit=${Math.min(100, Math.max(1, limit))}`); return (data.pulls || []).map((p: any) => ({ ...p, time: p.time || (p.createdAt ? formatDistanceToNow(new Date(p.createdAt), { addSuffix: true }) : '') })); }, staleTime: 30_000, refetchIntervalInBackground: false, refetchOnMount: 'always', refetchOnReconnect: true, retry: 6, retryDelay: attempt => Math.min(1500 * 2 ** attempt, 15000) }); }
export function useHallOfFame(limit = 5) { return useQuery({ queryKey: ['hall-of-fame', limit], queryFn: async () => { const data = await request<{ pulls: any[] }>(`/catalog/hall-of-fame?limit=${Math.min(50, Math.max(1, limit))}`); return (data.pulls || []).map((p: any) => ({ ...p, time: p.time || (p.createdAt ? formatDistanceToNow(new Date(p.createdAt), { addSuffix: true }) : '') })); }, staleTime: 60_000, refetchIntervalInBackground: false, refetchOnMount: 'always', refetchOnReconnect: true, retry: 6, retryDelay: attempt => Math.min(1500 * 2 ** attempt, 15000) }); }
export function useGodPulls() { return useQuery({ queryKey: ['god-pulls-catalog'], queryFn: async () => { const data = await request<{ cards: any[] }>('/catalog/god-pulls'); return data.cards || []; }, staleTime: 600_000, refetchIntervalInBackground: false, refetchOnMount: 'always', refetchOnReconnect: true, retry: 6, retryDelay: attempt => Math.min(1500 * 2 ** attempt, 15000) }); }
