import React from 'react';
import { motion } from 'framer-motion';
import { ChevronDown, Plus, Shield } from 'lucide-react';
import { useAuth, useUserStats } from '../hooks/useAuth';
import { useBalance } from '../hooks/useBalance';

type Page = 'home' | 'upgrader' | 'battle' | 'exchanger' | 'inventory' | 'profile';
interface NavbarProps { currentPage: Page; onPageChange: (page: Page) => void; openAuthModal: (tab: 'login' | 'signup') => void; onProfileOpen: () => void; onDepositOpen: () => void; }
const navTabs: { id: Page; label: string }[] = [
  { id: 'home', label: 'Packs' }, { id: 'upgrader', label: 'Upgrader' }, { id: 'battle', label: 'Pack Battle' }, { id: 'exchanger', label: 'Exchanger' }, { id: 'inventory', label: 'My Collection' },
];
export const Navbar: React.FC<NavbarProps> = React.memo(({ currentPage, onPageChange, openAuthModal, onProfileOpen, onDepositOpen }) => {
 const { user, isAuthenticated, isLoading: authLoading } = useAuth(); const { stats } = useUserStats(user?.id, user?.email, user?.displayName, user?.emailVerified); const { balance: liveBalance, isLoading: balanceLoading } = useBalance(user?.id); const isAdminUser = stats?.role === 'admin';
 return <nav className="fixed top-0 left-0 right-0 z-50 h-14 flex items-center border-b border-white/5 bg-[#0d0e14] shadow-[0_2px_20px_rgba(0,0,0,.6)]"><div className="w-full px-4 lg:px-6 flex items-center justify-between gap-4"><button onClick={() => onPageChange('home')} className="flex items-center gap-2"><img src="/favicon.ico" alt="PocketPull" className="w-8 h-8 rounded-full"/><span className="text-lg font-display bg-gradient-to-r from-[#00c8ff] to-[#9b5cff] bg-clip-text text-transparent">POCKETPULL</span></button><div className="hidden lg:flex items-center gap-1 flex-1 justify-center">{navTabs.map(tab => <button key={tab.id} onClick={() => onPageChange(tab.id)} className={`relative px-3 py-2 text-sm font-bold uppercase tracking-wider ${currentPage === tab.id ? 'text-[#00c8ff]' : 'text-gray-400 hover:text-white'}`}>{tab.label}{currentPage === tab.id && <motion.div layoutId="nav-indicator" className="absolute bottom-0 left-0 right-0 h-0.5 bg-[#00c8ff]"/>}</button>)}</div><div className="flex items-center gap-2">{authLoading || (isAuthenticated && !stats) ? <div className="w-28 h-8 rounded-lg bg-white/5 animate-pulse"/> : isAuthenticated ? <>{isAdminUser && <button onClick={() => window.open('/admin','_blank')} className="hidden md:flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs text-[#9b5cff] border border-[#9b5cff]/40"><Shield size={13}/> Admin</button>}<button onClick={onDepositOpen} className="flex items-center gap-1 bg-green-500/10 border border-green-500/20 rounded-full px-3 py-1.5"><Plus size={12} className="text-green-400"/><span className="text-green-400 text-xs font-bold">{balanceLoading ? '…' : `$${liveBalance.toFixed(2)}`}</span></button><button onClick={onProfileOpen} className="hidden md:flex items-center gap-2 bg-white/5 border border-white/10 rounded-lg px-3 py-1.5"><span className="text-xs text-gray-300">{stats?.displayName || user?.displayName || user?.email || 'Trainer'}</span><ChevronDown size={12}/></button></> : <><button onClick={() => openAuthModal('login')} className="hidden md:block px-4 py-1.5 text-sm text-gray-400">Login</button><button onClick={() => openAuthModal('signup')} className="px-4 py-1.5 bg-[#00c8ff] text-black text-sm font-bold rounded-lg">SIGN UP</button></>}</div></div></nav>;
});
