import React from 'react';
import { motion } from 'framer-motion';
import { ChevronDown, Plus, Shield } from 'lucide-react';
import { useAuth, useUserStats } from '../hooks/useAuth';
import { useBalance } from '../hooks/useBalance';


type Page = 'home' | 'upgrader' | 'battle' | 'exchanger' | 'inventory' | 'profile' | 'vault' | 'brawl' | 'shop';
interface NavbarProps { currentPage: Page; onPageChange: (page: Page) => void; openAuthModal: (tab: 'login' | 'signup') => void; onProfileOpen: () => void; onDepositOpen: () => void; }
const navTabs: { id: Page; label: string }[] = [
  { id: 'home', label: 'Packs' }, { id: 'upgrader', label: 'Upgrader' }, { id: 'battle', label: 'Pack Battle' }, { id: 'exchanger', label: 'Exchanger' }, { id: 'inventory', label: 'My Collection' }, { id: 'brawl', label: 'Poke Brawl' }, { id: 'shop', label: 'Shop' },
];
export const Navbar: React.FC<NavbarProps> = React.memo(({ currentPage, onPageChange, openAuthModal, onProfileOpen, onDepositOpen }) => {
 const { user, isAuthenticated, isLoading: authLoading } = useAuth(); const { stats } = useUserStats(user?.id, user?.email, user?.displayName, user?.emailVerified); const { balance: liveBalance, isLoading: balanceLoading } = useBalance(user?.id); const isAdminUser = stats?.role === 'admin';
 const avatarUrl = stats?.avatarUrl || (user as any)?.photoURL || (user as any)?.avatarUrl || '';
 const profileName = stats?.displayName || user?.displayName || user?.email || 'Trainer';
 const initials = profileName.trim().slice(0, 1).toUpperCase();
 return <nav className="fixed top-0 left-0 right-0 z-50 h-14 flex items-center border-b border-white/10 bg-[#080c14]/75 backdrop-blur-md shadow-[0_2px_24px_rgba(0,0,0,.5)]"><div className="w-full px-4 lg:px-6 flex items-center justify-between gap-4"><button onClick={() => onPageChange('home')} className="flex items-center gap-2"><img src="/favicon.ico" alt="PocketPull" className="w-8 h-8 rounded-full"/><span className="text-lg font-display bg-gradient-to-r from-[#00d4ff] to-[#7c5fff] bg-clip-text text-transparent tracking-widest">POCKETPULL</span></button><div className="hidden lg:flex items-center gap-1 flex-1 justify-center">{navTabs.map(tab => <button key={tab.id} onClick={() => onPageChange(tab.id)} className={`relative px-3 py-2 text-sm font-bold uppercase tracking-wider transition-colors ${currentPage === tab.id ? 'text-[#00d4ff]' : 'text-gray-500 hover:text-gray-200'}`}>{tab.label}{currentPage === tab.id && <motion.div layoutId="nav-indicator" className="absolute bottom-0 left-0 right-0 h-0.5 bg-gradient-to-r from-[#00d4ff] to-[#7c5fff]"/>}</button>)}</div><div className="flex items-center gap-2">{authLoading || (isAuthenticated && !stats) ? <div className="w-28 h-8 rounded-full bg-white/5 animate-pulse"/> : isAuthenticated ? <>{isAdminUser && <button onClick={() => window.open('/admin','_blank')} className="hidden md:flex items-center gap-1.5 h-8 px-4 rounded-full text-xs font-bold text-white bg-[#7c5fff]/20 border border-[#7c5fff]/50 hover:bg-[#7c5fff]/30 transition-colors"><Shield size={13}/> Admin</button>}<button onClick={onDepositOpen} className="flex items-center gap-1.5 h-8 bg-green-500 hover:bg-green-400 active:bg-green-600 rounded-full px-3 sm:px-4 transition-colors shadow-[0_0_12px_rgba(34,197,94,.4)]"><Plus size={12} className="text-black shrink-0"/><span className="text-black text-xs font-bold">{balanceLoading ? '…' : `$${liveBalance.toFixed(2)}`}</span></button><button onClick={onProfileOpen} className="flex items-center gap-2 h-8 bg-white/5 border border-white/10 hover:border-white/20 rounded-full pl-1 pr-3 transition-colors"><span className="flex h-6 w-6 shrink-0 items-center justify-center overflow-hidden rounded-full border border-[#00d4ff]/40 bg-[#0f1422] text-xs font-bold text-[#00d4ff]">{avatarUrl ? <img src={avatarUrl} alt="Profile" className="h-full w-full object-cover" onError={(event) => { event.currentTarget.style.display = 'none'; }} /> : initials}</span><span className="hidden md:inline text-xs text-gray-300">{profileName}</span><ChevronDown size={12} className="hidden md:block text-gray-500"/></button></> : <><button onClick={() => openAuthModal('login')} className="hidden md:block px-4 py-1.5 text-sm text-gray-400 hover:text-white transition-colors">Login</button><button onClick={() => openAuthModal('signup')} className="px-4 py-1.5 bg-[#00d4ff] hover:bg-[#00bbee] text-black text-sm font-bold rounded-full transition-colors shadow-[0_0_12px_rgba(0,212,255,.35)]">SIGN UP</button></>}</div></div></nav>;
});
